apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-cluster-role
rules:
  - apiGroups:
      - ""
      # Access to apps API is only required to support automatic cluster state management
      # when persistence (hot-restart) is enabled.
      - apps
    resources:
      - endpoints
      - pods
      - nodes
      - services
      # Access to statefulsets resource is only required to support automatic cluster state management
      # when persistence (hot-restart) is enabled.
      - statefulsets
    verbs:
      - get
      - list
      # Watching resources is only required to support automatic cluster state management
      # when persistence (hot-restart) is enabled.
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hazelcast-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hazelcast-cluster-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: infrastructure
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
  namespace: infrastructure
spec:
  clusterIP: None
  selector:
    app: hazelcast
  ports:
  - name: hazelcast
    port: 5701
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-config
  namespace: infrastructure
data:
  hazelcast.yaml: |
    hazelcast:
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-name: hazelcast-service
            namespace: infrastructure
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
  namespace: infrastructure
spec:
  serviceName: "hazelcast-service"
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast:5.4.0
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 5701
          name: hazelcast
        env:
        - name: HAZELCAST_KUBERNETES_SERVICE_NAME
          value: hazelcast-service
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /data/hazelcast.yaml
          subPath: hazelcast.yaml
      volumes:
      - name: config-volume
        configMap:
          name: hazelcast-config
