apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: postgres
  nfs:
    path: /mnt/data/postgres
    server: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: infrastructure
spec:
  storageClassName: postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infrastructure
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: infrastructure
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: postgres
      containers:
        - name: postgres
          image: postgres:15.6
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "sonarqube", "-h", "localhost"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "sonarqube", "-h", "localhost"]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: init
          configMap:
            name: init-databases-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-databases-configmap
  namespace: infrastructure
data:
  init.sql: |
    -- Create the teamcity database
    CREATE DATABASE teamcity;

    -- Grant full access to the postgres user on the teamcity database
    GRANT ALL PRIVILEGES ON DATABASE teamcity TO postgres;

    -- Create the bitbucket database
    CREATE DATABASE bitbucket;

    -- Grant full access to the postgres user on the bitbucket database
    GRANT ALL PRIVILEGES ON DATABASE bitbucket TO postgres;

    -- Create the jira database
    CREATE DATABASE jira;

    -- Grant full access to the postgres user on the jira database
    GRANT ALL PRIVILEGES ON DATABASE jira TO postgres;

    -- Create the sonarqube database
    CREATE DATABASE sonarqube;

    -- Grant full access to the postgres user on the sonarqube database
    GRANT ALL PRIVILEGES ON DATABASE sonarqube TO postgres;
