apiVersion: v1
kind: Service
metadata:
  name: teamcity
  namespace: teamcity
spec:
  type: NodePort
  selector:
    app: teamcity
  ports:
    - name: http
      protocol: TCP
      port: 8111
      targetPort: 8111
      nodePort: 30001
