apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-server-pv
  labels:
    app: teamcity-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: teamcity-server
  hostPath:
    path: /mnt/data/teamcity-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-data
  namespace: teamcity
spec:
  storageClassName: teamcity-server
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  namespace: teamcity
spec:
  selector:
    app: teamcity-server
  ports:
    - name: http
      protocol: TCP
      port: 8111
      targetPort: 8111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teamcity-server
  name: teamcity-server
  namespace: teamcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      initContainers:
        - name: set-data-dir-ownership
          image: alpine:3
          command: ["sh", "-c", "chown -R 1000:1000 /data/teamcity_server/datadir"]
          volumeMounts:
            - name: teamcity-server-data
              mountPath: /data/teamcity_server/datadir
      containers:
        - name: teamcity
          image: jetbrains/teamcity-server:2024.03
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - name: teamcity-server-data
              mountPath: /data/teamcity_server/datadir
          ports:
            - containerPort: 8111
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: 8111
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: 8111
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: teamcity-server-data
          persistentVolumeClaim:
            claimName: teamcity-server-data
