apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-server-data-pv
  labels:
    app: teamcity-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: teamcity-server-data
  hostPath:
    path: /mnt/data/teamcity-server-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-data
  namespace: teamcity
spec:
  storageClassName: teamcity-server-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-server-logs-pv
  labels:
    app: teamcity-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: teamcity-server-logs
  hostPath:
    path: /mnt/data/teamcity-server-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-logs
  namespace: teamcity
spec:
  storageClassName: teamcity-server-logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-server-temp-pv
  labels:
    app: teamcity-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: teamcity-server-temp
  hostPath:
    path: /mnt/data/teamcity-server-temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-server-temp
  namespace: teamcity
spec:
  storageClassName: teamcity-server-temp
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  namespace: teamcity
spec:
  type: NodePort
  selector:
    app: teamcity-server
  ports:
    - name: http
      protocol: TCP
      port: 8111
      targetPort: 8111
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teamcity-server
  name: teamcity-server
  namespace: teamcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      hostname: teamcity
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chown -R 1000:1000 /data/teamcity_server/datadir; chown -R 1000:1000 /opt/teamcity"]
          volumeMounts:
            - name: teamcity-server-data
              mountPath: /data/teamcity_server/datadir
            - name: teamcity-server-logs
              mountPath: /opt/teamcity/logs
            - name: teamcity-server-temp
              mountPath: /opt/teamcity/temp
      containers:
        - name: teamcity
          image: jetbrains/teamcity-server:2024.03.1
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 4
              memory: 8Gi
          volumeMounts:
            - name: teamcity-server-data
              mountPath: /data/teamcity_server/datadir
            - name: teamcity-server-logs
              mountPath: /opt/teamcity/logs
            - name: teamcity-server-temp
              mountPath: /opt/teamcity/temp
          ports:
            - containerPort: 8111
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: teamcity-server-data
          persistentVolumeClaim:
            claimName: teamcity-server-data
        - name: teamcity-server-logs
          persistentVolumeClaim:
            claimName: teamcity-server-logs
        - name: teamcity-server-temp
          persistentVolumeClaim:
            claimName: teamcity-server-temp
