apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teamcity
  name: teamcity
  namespace: teamcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity
  template:
    metadata:
      labels:
        app: teamcity
    spec:
      hostname: teamcity
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chown -R 1000:1000 /data/teamcity_server/datadir"]
          volumeMounts:
            - name: teamcity-data
              mountPath: /data/teamcity_server/datadir
      containers:
        - name: teamcity
          image: jetbrains/teamcity-server:2024.03.1
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 3
              memory: 3Gi
          volumeMounts:
            - name: teamcity-data
              mountPath: /data/teamcity_server/datadir
          ports:
            - containerPort: 8111
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: teamcity-data
          persistentVolumeClaim:
            claimName: teamcity-data
