apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
  namespace: teamcity
  labels:
    app: teamcity-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      containers:
      - name: teamcity-agent
        image: jetbrains/teamcity-agent:2024.03.1-linux
        env:
        - name: SERVER_URL
          value: http://teamcity:8111
        volumeMounts:
        - name: teamcity-agent-config
          mountPath: /data/teamcity_agent/conf
      volumes:
      - name: teamcity-agent-config
        emptyDir: {}
