apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-server-pv
  labels:
    app: jira-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: jira-server
  hostPath:
    path: /mnt/data/jira-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-server-data
  namespace: jira
spec:
  storageClassName: jira-server
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jira-server
  namespace: jira
spec:
  type: NodePort
  selector:
    app: jira-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira-server
  name: jira-server
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-server
  template:
    metadata:
      labels:
        app: jira-server
    spec:
      hostname: jira
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chown -R 1001:1001 /var/atlassian/application-data/jira; rm -f /var/atlassian/application-data/jira/docker-app.pid"]
          volumeMounts:
            - name: jira-server-data
              mountPath: /var/atlassian/application-data/jira
      containers:
        - name: jira
          image: atlassian/jira-software:9.13.1-ubi9-jdk17
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 4
              memory: 8Gi
          volumeMounts:
            - name: jira-server-data
              mountPath: /var/atlassian/application-data/jira
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: jira-server-data
          persistentVolumeClaim:
            claimName: jira-server-data
