apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      hostname: jira
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: [
            "sh", 
            "-c", 
            "chown -R 2001:2001 /var/atlassian/application-data/jira"
          ]
          volumeMounts:
            - name: jira-data
              mountPath: /var/atlassian/application-data/jira
      containers:
        - name: jira
          image: atlassian/jira-core:9.16.0-ubi9-jdk17
          securityContext:
            runAsUser: 2001
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 3
              memory: 3Gi
          volumeMounts:
            - name: jira-data
              mountPath: /var/atlassian/application-data/jira
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: http
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: http
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 30
      volumes:
        - name: jira-data
          persistentVolumeClaim:
            claimName: jira-data
