apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      hostname: jira
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chown -R 1001:1001 /var/atlassian/application-data/jira"]
          volumeMounts:
            - name: jira-data
              mountPath: /var/atlassian/application-data/jira
      containers:
        - name: jira
          image: atlassian/jira-software:9.13.1-ubi9-jdk17
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - name: jira-data
              mountPath: /var/atlassian/application-data/jira
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: jira-data
          persistentVolumeClaim:
            claimName: jira-data
