apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: jira
spec:
  type: NodePort
  selector:
    app: jira
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006
