apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bitbucket
  name: bitbucket
  namespace: bitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      hostname: bitbucket
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chown -R 2003:2003 /var/atlassian/application-data/bitbucket"]
          volumeMounts:
            - name: bitbucket-data
              mountPath: /var/atlassian/application-data/bitbucket
      containers:
        - name: bitbucket
          image: atlassian/bitbucket:8.19-jdk17
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - name: bitbucket-data
              mountPath: /var/atlassian/application-data/bitbucket
          ports:
            - containerPort: 7990
              name: http
              protocol: TCP
            - containerPort: 7999
              name: ssh
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: bitbucket-data
          persistentVolumeClaim:
            claimName: bitbucket-data
