apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bitbucket
  name: bitbucket
  namespace: bitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      hostname: bitbucket
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chown -R 2003:2003 /var/atlassian/application-data/bitbucket", "rm -f /var/atlassian/application-data/bitbucket/.lock"]
          volumeMounts:
            - name: bitbucket-data
              mountPath: /var/atlassian/application-data/bitbucket
      containers:
        - name: bitbucket
          image: atlassian/bitbucket:8.19-jdk17
          securityContext:
            runAsUser: 2003
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 2
              memory: 3Gi
          volumeMounts:
            - name: bitbucket-data
              mountPath: /var/atlassian/application-data/bitbucket
          ports:
            - containerPort: 7990
              name: http
              protocol: TCP
            - containerPort: 7999
              name: ssh
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: http
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: http
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 30
          env:
            - name: SEARCH_ENABLED
              value: "false"
            - name: PLUGIN_SEARCH_CONFIG_BASEURL
              value: http://opensearch.infrastructure:9200
            - name: JDBC_DRIVER
              value: org.postgresql.Driver
            - name: JDBC_URL
              value: jdbc:postgresql://postgres.infrastructure:5432/bitbucket
            - name: JDBC_USER
              value: postgres
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: bitbucket-data
          persistentVolumeClaim:
            claimName: bitbucket-data
