apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitbucket-data
  labels:
    app: bitbucket
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: bitbucket
  nfs:
    path: /mnt/data/bitbucket
    server: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-data
  namespace: bitbucket
spec:
  storageClassName: bitbucket
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
