apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  namespace: bitbucket
spec:
  type: NodePort
  selector:
    app: bitbucket
  ports:
    - name: http
      protocol: TCP
      port: 7990
      targetPort: 7990
      nodePort: 30002
    - name: ssh
      protocol: TCP
      port: 7999
      targetPort: 7999
      nodePort: 30003
