apiVersion: v1
kind: Pod
metadata:
  name: network-debug-pod
spec:
  containers:
  - name: network-debug-container
    image: busybox:1.34.0
    command: ["/bin/sh", "-c"]
    args:
    - sleep infinity
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
