apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      hostname: sonarqube
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chown -R 1000:1000 /opt/sonarqube/data"]
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
      containers:
        - name: sonarqube
          image: sonarqube:lts-community
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          env:
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://postgres.infrastructure/sonarqube
            - name: SONAR_JDBC_USERNAME
              value: postgres
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
