apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-server-data-pv
  labels:
    app: nexus-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nexus-server-data
  hostPath:
    path: /mnt/data/nexus-server-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-server-data
  namespace: nexus
spec:
  storageClassName: nexus-server-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-server-logs-pv
  labels:
    app: nexus-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nexus-server-logs
  hostPath:
    path: /mnt/data/nexus-server-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-server-logs
  namespace: nexus
spec:
  storageClassName: nexus-server-logs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-server-temp-pv
  labels:
    app: nexus-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nexus-server-temp
  hostPath:
    path: /mnt/data/nexus-server-temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-server-temp
  namespace: nexus
spec:
  storageClassName: nexus-server-temp
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-server
  namespace: nexus
spec:
  type: NodePort
  selector:
    app: nexus-server
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus-server
  name: nexus-server
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      hostname: nexus
      initContainers:
        - name: set-permissions
          image: alpine:3
          command: ["sh", "-c", "chmod -R 777 /nexus-data; chmod -R 777 /opt/sonatype/sonatype-work/nexus3"]
          volumeMounts:
            - name: nexus-server-data
              mountPath: /nexus-data
            - name: nexus-server-logs
              mountPath: /opt/sonatype/sonatype-work/nexus3/log
            - name: nexus-server-temp
              mountPath: /opt/sonatype/sonatype-work/nexus3/tmp
      containers:
        - name: nexus
          image: sonatype/nexus3:3.67.1-java11
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 4Gi
          volumeMounts:
            - name: nexus-server-data
              mountPath: /nexus-data
            - name: nexus-server-logs
              mountPath: /opt/sonatype/sonatype-work/nexus3/log
            - name: nexus-server-temp
              mountPath: /opt/sonatype/sonatype-work/nexus3/tmp
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /favicon.ico
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
      volumes:
        - name: nexus-server-data
          persistentVolumeClaim:
            claimName: nexus-server-data
        - name: nexus-server-logs
          persistentVolumeClaim:
            claimName: nexus-server-logs
        - name: nexus-server-temp
          persistentVolumeClaim:
            claimName: nexus-server-temp
