apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data
  labels:
    app: nexus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nexus
  nfs:
    path: /mnt/data/nexus
    server: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: nexus
spec:
  storageClassName: nexus
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
