apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30004
    - name: docker
      protocol: TCP
      port: 2000
      targetPort: 2000
      nodePort: 32000
